### ISSUE TITLE
Your Own IOT Service

### ISSUE THREAD

**Issue by alexwo** [alexwo/test01#26]
# Cloud deployment
Your challenge is to deploy your service to the SAP Cloud Platform CloudFoundry environment.

## Step 1 - Prepare service
First we must make sure that your new service implements the Open Service Broker API. 
- [Getting started](https://github.com/openservicebrokerapi/servicebroker/blob/master/gettingStarted.md)
- Endpoints to implement:
    - Catalog
    - Provision
    - Bind (Get, Create)
- Examples (Hint)
    - [Redis](https://github.com/pivotal-cf/cf-redis-broker/blob/2f0e9a8ebb1012a9be74bbef2d411b0b3b60352f/broker/broker.go)
    - [Example](https://developer.hpe.com/blog/using-open-service-broker-as-a-quick-and-easy-way-to-offer-everything-as)

1.1. Your service should return an active device from the http://localhost:9090/node API endpoint.
1.2. The device binding should return valid device credentials as

```
type Creds struct {
	Host     string `json:"host"`
	Port     int    `json:"port"`
	Username string `json:"username"`
	Password string `json:"password"`
}
```

## Step 2 - Deploy and try your service
Create a new [trial account](https://www.sap.com/products/cloud-platform.html) on SAP CF - (Hint) [tutorial](https://developers.sap.com/tutorials/hcp-create-trial-account.html).

[Deploy](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) the service and create a [service broker](https://docs.cloudfoundry.org/services/managing-service-brokers.html).

Lastly, create a [service instance](https://docs.cloudfoundry.org/devguide/services/managing-services.html) and [bind](http://cli.cloudfoundry.org/en-US/v6/bind-service.html) the app! 

If all works well go back to http://localhost:9090 and validate your service.
We will confirm that we can create a service instance, bind to it and that the device actually matches a real active and not over heating node.

## Step 3 - Validate your go code pass CI
In your selected "test01" repository create:
`.github/workflows/golangci-lint.yml`

```
GET /device/{id}/status
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.33

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
```

3.1 Make sure that your go code for this challenge is in the repository master branch.
3.2 Fix all LINT errors and create a new release
3.2 Pass the CI & Create a new release

If all works well go back to http://localhost:9090 and validate your release pass CI!

### Use full Links

https://github.com/golangci/golangci-lint
https://github.com/features/actions

Good luck!!!
