### ISSUE TITLE
Your Own IOT Service

### ISSUE THREAD

**Issue by alexwo** [alexwo/test01#41]
# Cloud deployment
Your challenge is to develop and deploy your own IoT service to the SAP Cloud Platform CloudFoundry environment.

## Step 1 - Prepare service
First we must make sure that your new service implements the Open Service Broker API. 

### The Open Service Broker API spec and what it's good for
https://ict.swisscom.ch/2019/12/open-service-broker-api/
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md

### Endpoints to implement:
    - Catalog (GET)
    - Provision (PUT)
    - Bind (GET, PUT)
---

### Requirements
1.1. Your service should allow to create a service instance that match an active device on http://localhost:9090/device.
1.2. The device binding should return the full device credentials as

```
{
  "credentials": {
    "connection_string": "device://438bcdca-c714-4c4a-8ba0-da975dec49f1/fNhptfPn",
    "device_type": "ROUTER",
    "id": "438bcdca-c714-4c4a-8ba0-da975dec49f1",
    "state": "Online",
  }
}
```
1.3. Your service should support basic authentication and allow access for admin:admin.
https://docs.iris-go.com/iris/security/basicauth

1.4. The create instance endpoint should support the device_type service instance param (ROUTER,MODEM,SWITCH)
See provisioning parameters:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#provisioning

### Recommended Golang libs
https://github.com/pmorie/osb-broker-lib
This library is most useful if you want to build your own broker from scratch

Golang server library:
https://www.iris-go.com/docs/#

Connecting to the /device endpoint 
https://github.com/go-resty/resty

osb-broker-lib with Golang server example:
```go
package main

import (
	"github.com/fatih/structs"
	"github.com/gavv/httpexpect"
	"github.com/kataras/iris/v12"
	"github.com/onsi/ginkgo"
	"github.wdf.sap.corp/cloudenablers/challenger/pkg/types"
	"github.wdf.sap.corp/cloudenablers/challenger/test/utils"
	"gopkg.in/yaml.v3"
	"net"
	"net/http"
	"time"
	osb "sigs.k8s.io/go-open-service-broker-client/v2"
)

func main() {
	app := iris.New()

	brokerAPIs := app.Party("/v2")
	{
		brokerAPIs.Get("/catalog", GetCatalog)
		brokerAPIs.Get("/service_instances/{instance_id:string}/service_bindings/{binding_id:string}", GetServiceBinding)
		brokerAPIs.Put("/service_instances/{instance_id:string}", CreateServiceInstance)
		brokerAPIs.Put("/service_instances/{instance_id:string}/service_bindings/{binding_id:string}", CreateServiceBinding)
	}
    serverPort := ":" + os.Getenv("PORT")
	app.Listen(serverPort)
}

func CreateServiceInstance(ctx iris.Context) {
    provisionDetails := &osb.ProvisionRequest{}
	instanceID = ctx.Params().Get("instance_id")
	deviceType := provisionDetails.Parameters["device_type"]
	iotBackendURL := "http://localhost:9090"
	apiCookieKey := "YOUR-API_COOKIE"
	
    reqBody, _ := ctx.GetBody()
    json.Unmarshal(reqBody, provisionDetails)
    //find device that matches thew provided deviceType in the provisionDetails
	deviceType := provisionDetails.Parameters["device_type"]
	client := getClient(iotBackendURL, apiCookieKey)
	pages := utils.GetDevicesPages(client) // Replace with your client impl (resty)
	for _, item := range pages {} // go over the device service pages result 
	ctx.JSON(&osb.ProvisionResponse{})
}



func GetServiceBinding(ctx iris.Context) {
	ctx.JSON(&osb.GetBindingResponse{
		Credentials:     structs.Map(foundItem),
	})
}

func CreateServiceBinding(ctx iris.Context) {
	ctx.JSON(&osb.BindResponse{
		Credentials:     structs.Map(foundItem),
	})
}

func GetCatalog(ctx iris.Context) {
response := &osb.CatalogResponse{}
data := `
---
services:
- name: your-iot-service
  id: 4f6e6cf6-ffdd-425f-a2c7-3c9258ad246e-alexwo
  description: The example service!
  bindable: true
  metadata:
    displayName: "Example service"
    imageUrl: https://avatars2.githubusercontent.com/u/19862012?s=200&v=4
  plans:
  - name: iot-service
    id: iot-service-alexwo
    description: The default plan for the service
    free: true
`
yaml.Unmarshal([]byte(data), &response)
ctx.JSON(response)
}
```

### Running Golang apps on cloudfoundry:

Define a correct port for the server to listen on:
```
  serverPort := ":" + os.Getenv("PORT")
  app.Listen(serverPort)
```

### define your cloudfoundry manifest.yml 
```
applications:
  - name: alexwo-challenge-app
    instances: 1
    buildpacks:
      - go_buildpack
```

## Step 2 - Deploy Your Service
Create a new [trial account](https://www.sap.com/products/cloud-platform.html) on SAP CF - (Hint) [tutorial](https://developers.sap.com/tutorials/hcp-create-trial-account.html).

[Deploy](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) the service and create a [service broker](https://docs.cloudfoundry.org/services/managing-service-brokers.html).

Lastly, create a [service instance](https://docs.cloudfoundry.org/devguide/services/managing-services.html) and [bind](http://cli.cloudfoundry.org/en-US/v6/bind-service.html) the app! 

If all works well go back to http://localhost:9090 and try out your service.

### Try out will try to confirm that

1. We can create a service instance -> select a real device from the "/device" list api
2. Bind to it -> get the credentials to use the device
3. Confirm the device actually matches an active & cool device (not above 29°C)

## Step 3 - Validate & pass CI
In your selected "test01" repository create:
`.github/workflows/golangci-lint.yml`

```
GET /device/{id}/status
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.33

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
```

3.1 Make sure that your go code for this challenge is in the repository master branch.

3.2 Fix all lint issues that  golangci will report (we want our code to be clean) 

3.3 Check that the CI pass (In github actions) & Create a new release

If all works well go back to http://localhost:9090 and validate your release pass CI!

### Use full Links

https://github.com/golangci/golangci-lint
https://github.com/features/actions

Good luck!!!
